// Uzbekistan-specific car brands and cities

export const CAR_BRANDS = [
    'Chevrolet',
    'Daewoo',
    'Kia',
    'Hyundai',
    'Toyota',
    'Lada (VAZ)',
    'BYD',
    'Chery',
    'Haval',
    'Geely',
    'MG',
    'Jetour',
    'Changan',
    'Exeed',
    'BMW',
    'Mercedes-Benz',
    'Audi',
    'Lexus',
    'Nissan',
    'Honda',
    'Volkswagen',
    'Skoda',
    'Renault',
    'Peugeot',
    'Boshqa',
] as const;

export const CITIES = [
    'Toshkent',
    'Samarqand',
    'Buxoro',
    'Namangan',
    "Andijon",
    "Farg'ona",
    'Qarshi',
    'Nukus',
    'Guliston',
    'Jizzax',
    'Navoiy',
    'Termiz',
    'Urganch',
    'Toshkent viloyati',
] as const;

export const YEARS = Array.from({ length: 30 }, (_, i) => 2026 - i);

// i18n translations
export const i18n = {
    uz: {
        appName: 'AvtoSotuv',
        home: 'Bosh sahifa',
        addListing: "E'lon joylash",
        myListings: "Mening e'lonlarim",
        profile: 'Profil',
        admin: 'Admin',
        search: 'Qidirish...',
        brand: 'Marka',
        allBrands: 'Barcha markalar',
        year: 'Yil',
        price: 'Narx',
        priceFrom: 'dan',
        priceTo: 'gacha',
        city: 'Shahar',
        allCities: 'Barcha shaharlar',
        mileage: 'Probeg',
        description: 'Tavsif',
        title: 'Nomi',
        photos: 'Rasmlar',
        showPhone: "Telefonni ko'rish",
        views: "Ko'rishlar",
        create: 'Joylash',
        delete: "O'chirish",
        sold: 'Sotilgan',
        active: 'Aktiv',
        noListings: "E'lonlar topilmadi",
        loading: 'Yuklanmoqda...',
        error: 'Xatolik yuz berdi',
        maxListings: "Siz maksimal 3 ta aktiv e'lon joylashingiz mumkin",
        cooldown: "24 soat ichida faqat 1 ta e'lon joylash mumkin",
        duplicate: "Bu e'lon allaqachon mavjud",
        blocked: 'Sizning hisobingiz bloklangan',
        uploadPhotos: 'Rasm yuklang (kamida 1 ta)',
        confirm: 'Tasdiqlash',
        cancel: 'Bekor qilish',
        next: 'Keyingi',
        back: 'Orqaga',
        step: 'Qadam',
        carInfo: "Mashina ma'lumotlari",
        imageUpload: 'Rasm yuklash',
        review: "Ko'rib chiqish",
        successCreate: "E'lon muvaffaqiyatli joylashdi!",
        deleteConfirm: "E'lonni o'chirishni xohlaysizmi?",
        yes: 'Ha',
        no: "Yo'q",
        km: 'km',
        sum: "so'm",
        filter: 'Filter',
        sort: 'Saralash',
        newest: 'Eng yangi',
        cheapest: 'Eng arzon',
        expensive: 'Eng qimmat',
        // Admin
        totalUsers: 'Jami foydalanuvchilar',
        totalListings: "Jami e'lonlar",
        activeListings: "Aktiv e'lonlar",
        todayViews: "Bugungi ko'rishlar",
        blockUser: 'Bloklash',
        unblockUser: 'Blokdan chiqarish',
        deleteListing: "E'lonni o'chirish",
        users: 'Foydalanuvchilar',
        listings: "E'lonlar",
        stats: 'Statistika',
    },
    ru: {
        appName: 'АвтоСотув',
        home: 'Главная',
        addListing: 'Добавить объявление',
        myListings: 'Мои объявления',
        profile: 'Профиль',
        admin: 'Админ',
        search: 'Поиск...',
        brand: 'Марка',
        allBrands: 'Все марки',
        year: 'Год',
        price: 'Цена',
        priceFrom: 'от',
        priceTo: 'до',
        city: 'Город',
        allCities: 'Все города',
        mileage: 'Пробег',
        description: 'Описание',
        title: 'Название',
        photos: 'Фотографии',
        showPhone: 'Показать телефон',
        views: 'Просмотры',
        create: 'Создать',
        delete: 'Удалить',
        sold: 'Продано',
        active: 'Активно',
        noListings: 'Объявления не найдены',
        loading: 'Загрузка...',
        error: 'Произошла ошибка',
        maxListings: 'Максимум 3 активных объявления',
        cooldown: 'Только 1 объявление за 24 часа',
        duplicate: 'Такое объявление уже существует',
        blocked: 'Ваш аккаунт заблокирован',
        uploadPhotos: 'Загрузите фото (минимум 1)',
        confirm: 'Подтвердить',
        cancel: 'Отмена',
        next: 'Далее',
        back: 'Назад',
        step: 'Шаг',
        carInfo: 'Данные автомобиля',
        imageUpload: 'Загрузка фото',
        review: 'Просмотр',
        successCreate: 'Объявление успешно создано!',
        deleteConfirm: 'Удалить объявление?',
        yes: 'Да',
        no: 'Нет',
        km: 'км',
        sum: 'сум',
        filter: 'Фильтр',
        sort: 'Сортировка',
        newest: 'Новые',
        cheapest: 'Дешёвые',
        expensive: 'Дорогие',
        // Admin
        totalUsers: 'Всего пользователей',
        totalListings: 'Всего объявлений',
        activeListings: 'Активных объявлений',
        todayViews: 'Просмотры сегодня',
        blockUser: 'Заблокировать',
        unblockUser: 'Разблокировать',
        deleteListing: 'Удалить объявление',
        users: 'Пользователи',
        listings: 'Объявления',
        stats: 'Статистика',
    },
} as const;

export type Locale = keyof typeof i18n;
export type TranslationKey = keyof typeof i18n.uz;
